spring:
  application:
    name: clearing-settlement-service

  datasource:
    url: jdbc:mysql://localhost:3306/clearing_settlement_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  cloud:
    stream:
      default-binder: kafka
      function:
        definition: paymentApproved
      bindings:
        paymentApproved-in-0:
          destination: card.payment.approved
          group: clearing-settlement-group
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 9091

logging:
  level:
    com.card.payment: DEBUG

bank:
  service:
    url: http://localhost:8086
  settlement:
    from-account: 9999999999
